description: Ubuntu 14.04 gnome flashback Desktop version contains oracle jdk 8.
provision: shell
hint: Maybe restart needed because new profile.d scripts will be added they take effect after restart.
username: vagrant
password: vagrant
size: 1.0 GB
image: https://vagrantcloud.com/pussinboots/ubuntu-truly-jdk8
packages:
    - java8
    - sbt
    - rpm
    - createrepo
    - cs (conscript)
    - flashback (gnome flashback desktop 2d)
    - heroku
    - idea13 (ultimate)
    - nodejs
    - play223 (play 2.2.3 version)
    - softcover-nonstop (softcover fork that support nonstopemode for building pdfs)
    - sublime3 (sublime 3 test editor)
    - travis
